[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"
solc_version = "0.8.21"

fs_permissions = [{ access = "read", path = "./bytecode"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config